### ISSUE TITLE
Spotify link is dead

### ISSUE THREAD

**Issue by Nintendofan885** [exrem/website#1]
Hi. FYI looks like sptfy.com is dead (I thought it was a typo at first) so you might want to replace it in [/middleware/redirect.ts](../blob/main/middleware/redirect.ts)

**Comment by exrem** [comment]
oh, hai~! :3
yeah i've kinda abandoned the website lol, and have completely forgorren about it; thank you! :D

**Comment by Nintendofan885** [comment]
heh, no problem :)
